// Builds src/lib/gw2/fishing.ts: the Guild Wars 2 fishing catch tables, grouped
// by region, sourced entirely from the official GW2 API.
//
// Source: /v2/achievements/categories/317 (Fishing). Each "X Fisher" /
// "Avid X Fisher" achievement's item bits carry the structured catch data:
//   id   -> the caught fish (an item: name, rarity, icon)
//   text -> "Found in the waters of <region>.<br>Fishing Hole: <hole><br>
//            Favored Bait: <bait><br>Time of Day: <time>"
// The caught fish are account-bound (no trading-post value), so these pages are
// catch / collection guides for the Avid Fisher achievements, not gold farms.
//
// Run: node scripts/sync-fishing.mjs

import { writeFile } from "node:fs/promises";

const API = "https://api.guildwars2.com/v2";
const OUT = new URL("../src/lib/gw2/fishing.ts", import.meta.url);
const UA = { "User-Agent": "buildop sync (buildop.app)" };

async function gw2(path) {
  const r = await fetch(`${API}/${path}`, { headers: UA });
  if (!r.ok) throw new Error(`GW2 API ${path} -> ${r.status}`);
  return r.json();
}

// Fetch a large id list in chunks (the API caps at 200 ids per request).
async function gw2Many(endpoint, ids) {
  const out = [];
  for (let i = 0; i < ids.length; i += 200) {
    out.push(...(await gw2(`${endpoint}?ids=${ids.slice(i, i + 200).join(",")}`)));
  }
  return out;
}

const slugify = (s) =>
  s.toLowerCase().replace(/'/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function parseBit(text) {
  const t = text || "";
  const grab = (re) => (t.match(re) || [])[1]?.trim() || "Any";
  return {
    hole: grab(/Fishing Hole:\s*([^<]+)/),
    bait: grab(/Favored Bait:\s*([^<]+)/),
    time: grab(/Time of Day:\s*([^<]+)/),
  };
}

// Region key = achievement name minus the "Avid " prefix and " Fisher" suffix,
// so a region's base + Avid collections merge into one group.
const regionKey = (name) => name.replace(/^Avid\s+/, "").replace(/\s+Fisher$/, "");

console.log("Fetching fishing achievements…");
const cat = await gw2("achievements/categories/317");
const achIds = cat.achievements.map((a) => (typeof a === "object" ? a.id : a));
const achs = await gw2Many("achievements", achIds);

/** @type {Map<string, {name:string, achievementIds:number[], fish:Map<number,{id:number,hole:string,bait:string,time:string}>}>} */
const groups = new Map();
for (const a of achs) {
  if (!/Fisher$/.test(a.name)) continue; // skip the Aquatic Collector meta-collections
  if (!a.bits?.some((b) => b.type === "Item")) continue;
  const key = regionKey(a.name);
  if (!groups.has(key)) groups.set(key, { name: key, achievementIds: [], fish: new Map() });
  const g = groups.get(key);
  g.achievementIds.push(a.id);
  for (const b of a.bits) {
    if (b.type !== "Item" || g.fish.has(b.id)) continue;
    g.fish.set(b.id, { id: b.id, ...parseBit(b.text) });
  }
}

// Resolve item details (name, rarity, icon) for every distinct fish.
const allIds = [...new Set([...groups.values()].flatMap((g) => [...g.fish.keys()]))];
console.log(`Resolving ${allIds.length} fish items…`);
const items = await gw2Many("items", allIds);
const itemById = new Map(items.map((it) => [it.id, it]));

const RARITY_ORDER = ["Junk", "Basic", "Fine", "Masterwork", "Rare", "Exotic", "Ascended", "Legendary"];

const regions = [...groups.values()]
  .map((g) => {
    const fish = [...g.fish.values()]
      .map((f) => {
        const it = itemById.get(f.id);
        return {
          id: f.id,
          name: it?.name ?? `Item ${f.id}`,
          rarity: it?.rarity ?? "Basic",
          icon: it?.icon ?? "",
          hole: f.hole,
          bait: f.bait,
          time: f.time,
        };
      })
      .sort(
        (a, b) =>
          a.hole.localeCompare(b.hole) ||
          RARITY_ORDER.indexOf(a.rarity) - RARITY_ORDER.indexOf(b.rarity) ||
          a.name.localeCompare(b.name),
      );
    return {
      slug: slugify(g.name),
      name: g.name,
      achievementIds: g.achievementIds.sort((a, b) => a - b),
      fish,
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const bySlug = Object.fromEntries(regions.map((r) => [r.slug, r]));

const ts = `// AUTO-GENERATED by scripts/sync-fishing.mjs — do not edit by hand.
// Guild Wars 2 fishing catch tables grouped by region, from the official GW2 API
// (achievements category 317). The caught fish are account-bound, so these are
// catch / collection guides for the Avid Fisher achievements.

export type Fish = {
  /** Item id of the caught fish. */
  id: number;
  name: string;
  /** GW2 rarity: Basic, Fine, Masterwork, Rare, Exotic, Ascended, Legendary. */
  rarity: string;
  /** Item icon render URL. */
  icon: string;
  /** Fishing hole / water type where it bites, e.g. "Lake Fish", "Open Water". */
  hole: string;
  /** Favored bait, or "Any". */
  bait: string;
  /** Time of day, e.g. "Any", "Daytime", "Nighttime", "Dusk/Dawn". */
  time: string;
};

export type FishingRegion = {
  slug: string;
  /** Region name as used by the Fisher achievements, e.g. "Krytan", "Orrian". */
  name: string;
  /** The "X Fisher" / "Avid X Fisher" achievement ids this region covers. */
  achievementIds: number[];
  fish: Fish[];
};

export const FISHING_REGIONS: Record<string, FishingRegion> = ${JSON.stringify(bySlug, null, 2)};

/** All regions, alphabetical by name. */
export const FISHING_REGION_LIST: FishingRegion[] = Object.values(FISHING_REGIONS);
`;

await writeFile(OUT, ts, "utf8");
console.log(
  `Wrote ${regions.length} fishing regions, ${allIds.length} fish.\n` +
    regions.map((r) => `  ${r.slug} (${r.fish.length})`).join("\n"),
);
