// AUTO-GENERATED by scripts/sync-map-waypoints.mjs — do not edit by hand.
// One representative waypoint per Tyria map (nearest the map centre) with its
// in-game chat code, plus a region -> map-names index. Source: GW2 API
// /v2/continents/1/floors/1 (chat_link is provided directly by the API).

export type MapWaypoint = {
  name: string;
  chat: string;
  coord: [number, number];
  /** Map bounding rectangle [[x0,y0],[x1,y1]] in continent coordinates. */
  rect: [[number, number], [number, number]];
};

export const MAP_WAYPOINTS: Record<string, MapWaypoint> = {
  "Amnytas": {
    "name": "Bastion of the Celestial Waypoint",
    "chat": "[&BAoOAAA=]",
    "coord": [
      24086,
      19984
    ],
    "rect": [
      [
        22614,
        18938
      ],
      [
        25558,
        21882
      ]
    ]
  },
  "Arborstone": {
    "name": "Arborstone Waypoint",
    "chat": "[&BGMNAAA=]",
    "coord": [
      29845,
      101425
    ],
    "rect": [
      [
        29185,
        100890
      ],
      [
        33025,
        103450
      ]
    ]
  },
  "Auric Basin": {
    "name": "Forgotten City Waypoint",
    "chat": "[&BMYHAAA=]",
    "coord": [
      34318,
      33966
    ],
    "rect": [
      [
        33280,
        32512
      ],
      [
        35328,
        35328
      ]
    ]
  },
  "Bava Nisos": {
    "name": "Mantle's Arrival Waypoint",
    "chat": "[&BGEPAAA=]",
    "coord": [
      36051,
      11654
    ],
    "rect": [
      [
        35720,
        10344
      ],
      [
        38280,
        12904
      ]
    ]
  },
  "Bitterfrost Frontier": {
    "name": "Sorrow's Eclipse Waypoint",
    "chat": "[&BH0JAAA=]",
    "coord": [
      54984,
      23970
    ],
    "rect": [
      [
        53504,
        23040
      ],
      [
        56576,
        24576
      ]
    ]
  },
  "Bjora Marches": {
    "name": "Still Waters Speaking Waypoint",
    "chat": "[&BDkMAAA=]",
    "coord": [
      56616,
      17815
    ],
    "rect": [
      [
        54911,
        16972
      ],
      [
        59391,
        19148
      ]
    ]
  },
  "Black Citadel": {
    "name": "Gladium Waypoint",
    "chat": "[&BKQDAAA=]",
    "coord": [
      57120,
      31106
    ],
    "rect": [
      [
        56320,
        29952
      ],
      [
        57856,
        32000
      ]
    ]
  },
  "Blazeridge Steppes": {
    "name": "Refuge Sanctum Waypoint",
    "chat": "[&BAUCAAA=]",
    "coord": [
      62795,
      30752
    ],
    "rect": [
      [
        61952,
        28544
      ],
      [
        64000,
        32640
      ]
    ]
  },
  "Bloodstone Fen": {
    "name": "Zealot's Overlook Waypoint",
    "chat": "[&BE4JAAA=]",
    "coord": [
      35482,
      30692
    ],
    "rect": [
      [
        34816,
        30338
      ],
      [
        36352,
        30978
      ]
    ]
  },
  "Bloodtide Coast": {
    "name": "Firthside Vigil Waypoint",
    "chat": "[&BKoBAAA=]",
    "coord": [
      49401,
      34072
    ],
    "rect": [
      [
        48000,
        32256
      ],
      [
        50432,
        35456
      ]
    ]
  },
  "Brisban Wildlands": {
    "name": "Brilitine Waypoint",
    "chat": "[&BGEAAAA=]",
    "coord": [
      40166,
      31857
    ],
    "rect": [
      [
        38656,
        30848
      ],
      [
        42112,
        33536
      ]
    ]
  },
  "Caledon Forest": {
    "name": "Mabon Waypoint",
    "chat": "[&BDoBAAA=]",
    "coord": [
      42869,
      34533
    ],
    "rect": [
      [
        42112,
        32512
      ],
      [
        44032,
        36480
      ]
    ]
  },
  "Closing Ceremony": {
    "name": "Crown Pavilion Waypoint",
    "chat": "[&BCwDAAA=]",
    "coord": [
      43628,
      27230
    ],
    "rect": [
      [
        43008,
        26240
      ],
      [
        44928,
        28032
      ]
    ]
  },
  "Cursed Shore": {
    "name": "Meddler's Waypoint",
    "chat": "[&BB4DAAA=]",
    "coord": [
      43854,
      43752
    ],
    "rect": [
      [
        42880,
        41600
      ],
      [
        44928,
        45696
      ]
    ]
  },
  "Diessa Plateau": {
    "name": "Blasted Moors Waypoint",
    "chat": "[&BNoAAAA=]",
    "coord": [
      57831,
      28790
    ],
    "rect": [
      [
        56320,
        27648
      ],
      [
        59904,
        29952
      ]
    ]
  },
  "Divinity's Reach": {
    "name": "Palace Waypoint",
    "chat": "[&BCkDAAA=]",
    "coord": [
      44036,
      27193
    ],
    "rect": [
      [
        43008,
        26240
      ],
      [
        44928,
        28032
      ]
    ]
  },
  "Domain of Istan": {
    "name": "Chalon Docks Waypoint",
    "chat": "[&BAkLAAA=]",
    "coord": [
      57793,
      61028
    ],
    "rect": [
      [
        55318,
        59916
      ],
      [
        59158,
        63756
      ]
    ]
  },
  "Draconis Mons": {
    "name": "Ancient Hollow Waypoint",
    "chat": "[&BNUJAAA=]",
    "coord": [
      36589,
      41019
    ],
    "rect": [
      [
        34718,
        39284
      ],
      [
        38558,
        43124
      ]
    ]
  },
  "Dragon's End": {
    "name": "Harvest Complex Waypoint",
    "chat": "[&BKAMAAA=]",
    "coord": [
      34181,
      103953
    ],
    "rect": [
      [
        33126,
        101838
      ],
      [
        35302,
        105550
      ]
    ]
  },
  "Dragon's Stand": {
    "name": "Dragon's Domain Central Waypoint",
    "chat": "[&BJcIAAA=]",
    "coord": [
      35436,
      37715
    ],
    "rect": [
      [
        34048,
        36096
      ],
      [
        37120,
        38784
      ]
    ]
  },
  "Dredgehaunt Cliffs": {
    "name": "Kenning Testing Ground Waypoint",
    "chat": "[&BF4CAAA=]",
    "coord": [
      53575,
      32721
    ],
    "rect": [
      [
        52224,
        31360
      ],
      [
        54528,
        34560
      ]
    ]
  },
  "Drizzlewood Coast": {
    "name": "Forward Camp Waypoint",
    "chat": "[&BHIMAAA=]",
    "coord": [
      50444,
      19441
    ],
    "rect": [
      [
        50128,
        17809
      ],
      [
        52304,
        22289
      ]
    ]
  },
  "Dry Top": {
    "name": "Restoration Refuge Waypoint",
    "chat": "[&BIgHAAA=]",
    "coord": [
      37731,
      32727
    ],
    "rect": [
      [
        36608,
        30976
      ],
      [
        38656,
        33536
      ]
    ]
  },
  "Ember Bay": {
    "name": "Crumbling Trail Waypoint",
    "chat": "[&BGAJAAA=]",
    "coord": [
      39809,
      45115
    ],
    "rect": [
      [
        37374,
        43518
      ],
      [
        41214,
        47358
      ]
    ]
  },
  "Eternity's Garden": {
    "name": "Sanctum Exterior Waypoint",
    "chat": "[&BPAPAAA=]",
    "coord": [
      4867,
      61003
    ],
    "rect": [
      [
        3130,
        59945
      ],
      [
        5690,
        63145
      ]
    ]
  },
  "Eye of the North": {
    "name": "Eye of the North Waypoint",
    "chat": "[&BAkMAAA=]",
    "coord": [
      57865,
      21795
    ],
    "rect": [
      [
        57344,
        21248
      ],
      [
        58624,
        22528
      ]
    ]
  },
  "Fields of Ruin": {
    "name": "Wreckage of Bloodgorge Watch Waypoint",
    "chat": "[&BE4BAAA=]",
    "coord": [
      63113,
      34430
    ],
    "rect": [
      [
        61440,
        32640
      ],
      [
        64512,
        35712
      ]
    ]
  },
  "Fireheart Rise": {
    "name": "Keeper's Waypoint",
    "chat": "[&BCYCAAA=]",
    "coord": [
      58276,
      25871
    ],
    "rect": [
      [
        56576,
        24832
      ],
      [
        59904,
        27648
      ]
    ]
  },
  "Frostgorge Sound": {
    "name": "Ridgerock Camp Waypoint",
    "chat": "[&BIMCAAA=]",
    "coord": [
      55253,
      26550
    ],
    "rect": [
      [
        53504,
        24576
      ],
      [
        56576,
        27648
      ]
    ]
  },
  "Gendarran Fields": {
    "name": "Oogooth Waypoint",
    "chat": "[&BOIAAAA=]",
    "coord": [
      48089,
      29884
    ],
    "rect": [
      [
        46208,
        28672
      ],
      [
        50432,
        30720
      ]
    ]
  },
  "Grothmar Valley": {
    "name": "Blood Keep Waypoint",
    "chat": "[&BBsMAAA=]",
    "coord": [
      60427,
      18848
    ],
    "rect": [
      [
        59392,
        17504
      ],
      [
        62592,
        20064
      ]
    ]
  },
  "Gyala Delve": {
    "name": "Behemoth's Gap Waypoint",
    "chat": "[&BJINAAA=]",
    "coord": [
      37424,
      102153
    ],
    "rect": [
      [
        36677,
        100479
      ],
      [
        38853,
        104191
      ]
    ]
  },
  "Harathi Hinterlands": {
    "name": "Recovery Camp Waypoint",
    "chat": "[&BKwAAAA=]",
    "coord": [
      47863,
      27455
    ],
    "rect": [
      [
        46208,
        25856
      ],
      [
        49408,
        28672
      ]
    ]
  },
  "Hoelbrak": {
    "name": "Peeta's Waypoint",
    "chat": "[&BI8DAAA=]",
    "coord": [
      53314,
      30661
    ],
    "rect": [
      [
        52224,
        29696
      ],
      [
        54528,
        31360
      ]
    ]
  },
  "Inner Nayos": {
    "name": "Forward Bivouac Waypoint",
    "chat": "[&BHYOAAA=]",
    "coord": [
      21734,
      22801
    ],
    "rect": [
      [
        19435,
        21900
      ],
      [
        23147,
        24076
      ]
    ]
  },
  "Iron Marches": {
    "name": "Brandwatch Encampment Waypoint",
    "chat": "[&BOkBAAA=]",
    "coord": [
      61229,
      28081
    ],
    "rect": [
      [
        59904,
        25856
      ],
      [
        61952,
        29952
      ]
    ]
  },
  "Isle of Reflection": {
    "name": "Reflection Docks Waypoint",
    "chat": "[&BPMMAAA=]",
    "coord": [
      21852,
      104468
    ],
    "rect": [
      [
        21319,
        103145
      ],
      [
        23239,
        105705
      ]
    ]
  },
  "Janthir Syntri": {
    "name": "Sanguine Crater Waypoint",
    "chat": "[&BCwPAAA=]",
    "coord": [
      39237,
      15525
    ],
    "rect": [
      [
        38294,
        14082
      ],
      [
        41494,
        17154
      ]
    ]
  },
  "Kessex Hills": {
    "name": "Viathan Waypoint",
    "chat": "[&BBAAAAA=]",
    "coord": [
      43834,
      31419
    ],
    "rect": [
      [
        42112,
        30464
      ],
      [
        46208,
        32512
      ]
    ]
  },
  "Labyrinthine Cliffs": {
    "name": "Sky Docks Waypoint",
    "chat": "[&BB0HAAA=]",
    "coord": [
      55718,
      39278
    ],
    "rect": [
      [
        54958,
        38648
      ],
      [
        56494,
        40184
      ]
    ]
  },
  "Lake Doric": {
    "name": "Doric's Landing Waypoint",
    "chat": "[&BK0JAAA=]",
    "coord": [
      45005,
      27002
    ],
    "rect": [
      [
        44928,
        25472
      ],
      [
        46208,
        28032
      ]
    ]
  },
  "Lion's Arch": {
    "name": "Gate Hub Plaza Waypoint",
    "chat": "[&BBEEAAA=]",
    "coord": [
      49309,
      31223
    ],
    "rect": [
      [
        48000,
        30720
      ],
      [
        50432,
        32256
      ]
    ]
  },
  "Lion's Arch Aerodrome": {
    "name": "Aerodrome Waypoint",
    "chat": "[&BCAJAAA=]",
    "coord": [
      49331,
      32137
    ],
    "rect": [
      [
        47964,
        30806
      ],
      [
        50396,
        32342
      ]
    ]
  },
  "Lornar's Pass": {
    "name": "Afgar's Waypoint",
    "chat": "[&BFMGAAA=]",
    "coord": [
      51276,
      31884
    ],
    "rect": [
      [
        50432,
        29696
      ],
      [
        52224,
        34560
      ]
    ]
  },
  "Lost Precipice": {
    "name": "Central Precipice Waypoint",
    "chat": "[&BMIIAAA=]",
    "coord": [
      34235,
      30348
    ],
    "rect": [
      [
        33536,
        29696
      ],
      [
        34816,
        30976
      ]
    ]
  },
  "Lowland Shore": {
    "name": "Autumn's Vale Waypoint",
    "chat": "[&BC4PAAA=]",
    "coord": [
      41864,
      22648
    ],
    "rect": [
      [
        40119,
        21518
      ],
      [
        43959,
        24078
      ]
    ]
  },
  "Malchor's Leap": {
    "name": "Blighted Arch Waypoint",
    "chat": "[&BK4CAAA=]",
    "coord": [
      45132,
      40523
    ],
    "rect": [
      [
        43136,
        39552
      ],
      [
        47232,
        41600
      ]
    ]
  },
  "Metrica Province": {
    "name": "Rana Landing Complex Waypoint",
    "chat": "[&BEMAAAA=]",
    "coord": [
      40758,
      35413
    ],
    "rect": [
      [
        39936,
        33536
      ],
      [
        42112,
        36864
      ]
    ]
  },
  "Mistburned Barrens": {
    "name": "Alliance Staging Ground",
    "chat": "[&BFAPAAA=]",
    "coord": [
      34312,
      11578
    ],
    "rect": [
      [
        34063,
        10361
      ],
      [
        37903,
        12921
      ]
    ]
  },
  "Mount Maelstrom": {
    "name": "Oxbow Isle Waypoint",
    "chat": "[&BNECAAA=]",
    "coord": [
      52794,
      38992
    ],
    "rect": [
      [
        50560,
        37760
      ],
      [
        54400,
        40192
      ]
    ]
  },
  "New Kaineng City": {
    "name": "Ministry Ward Waypoint",
    "chat": "[&BBkNAAA=]",
    "coord": [
      26674,
      99438
    ],
    "rect": [
      [
        25000,
        98100
      ],
      [
        28840,
        100660
      ]
    ]
  },
  "Plains of Ashford": {
    "name": "Spirit Hunter Camp Waypoint",
    "chat": "[&BJkDAAA=]",
    "coord": [
      59896,
      30719
    ],
    "rect": [
      [
        57856,
        29952
      ],
      [
        61952,
        32000
      ]
    ]
  },
  "Queensdale": {
    "name": "Scaver Waypoint",
    "chat": "[&BEUDAAA=]",
    "coord": [
      44145,
      29194
    ],
    "rect": [
      [
        42624,
        28032
      ],
      [
        46208,
        30464
      ]
    ]
  },
  "Rata Sum": {
    "name": "Auxiliary Waypoint",
    "chat": "[&BLkEAAA=]",
    "coord": [
      38746,
      37236
    ],
    "rect": [
      [
        37376,
        36094
      ],
      [
        39936,
        38654
      ]
    ]
  },
  "Seitung Province": {
    "name": "Daigo Ward Waypoint",
    "chat": "[&BGUNAAA=]",
    "coord": [
      23191,
      101452
    ],
    "rect": [
      [
        21159,
        100457
      ],
      [
        24999,
        103145
      ]
    ]
  },
  "Shipwreck Strand": {
    "name": "Hullgarden Pier Waypoint",
    "chat": "[&BMwPAAA=]",
    "coord": [
      11661,
      59029
    ],
    "rect": [
      [
        9530,
        57385
      ],
      [
        12090,
        60585
      ]
    ]
  },
  "Siren's Landing": {
    "name": "Camp Reclamation Waypoint",
    "chat": "[&BO8JAAA=]",
    "coord": [
      49393,
      42605
    ],
    "rect": [
      [
        47002,
        41600
      ],
      [
        50330,
        42880
      ]
    ]
  },
  "Skywatch Archipelago": {
    "name": "Kestrel's Vow Waypoint",
    "chat": "[&BD8OAAA=]",
    "coord": [
      25402,
      23928
    ],
    "rect": [
      [
        23590,
        22650
      ],
      [
        27302,
        24826
      ]
    ]
  },
  "Snowden Drifts": {
    "name": "Torstvedt Homestead Waypoint",
    "chat": "[&BLsAAAA=]",
    "coord": [
      52847,
      28439
    ],
    "rect": [
      [
        50432,
        27648
      ],
      [
        54528,
        29696
      ]
    ]
  },
  "Southsun Cove": {
    "name": "Camp Karka Waypoint",
    "chat": "[&BNcGAAA=]",
    "coord": [
      45606,
      36767
    ],
    "rect": [
      [
        44288,
        35328
      ],
      [
        46976,
        37120
      ]
    ]
  },
  "Sparkfly Fen": {
    "name": "Toade's Head Waypoint",
    "chat": "[&BMsBAAA=]",
    "coord": [
      49398,
      37058
    ],
    "rect": [
      [
        48000,
        35456
      ],
      [
        50560,
        38784
      ]
    ]
  },
  "Starlit Weald": {
    "name": "Priory Expedition Waypoint",
    "chat": "[&BJ4PAAA=]",
    "coord": [
      7618,
      58836
    ],
    "rect": [
      [
        6330,
        57385
      ],
      [
        9530,
        59945
      ]
    ]
  },
  "Straits of Devastation": {
    "name": "Vesper Bell Waypoint",
    "chat": "[&BPICAAA=]",
    "coord": [
      49073,
      40069
    ],
    "rect": [
      [
        47232,
        38784
      ],
      [
        50560,
        41600
      ]
    ]
  },
  "Tangled Depths": {
    "name": "Ogre Camp Waypoint",
    "chat": "[&BMwHAAA=]",
    "coord": [
      36674,
      35238
    ],
    "rect": [
      [
        35328,
        33792
      ],
      [
        38656,
        36096
      ]
    ]
  },
  "The Echovald Wilds": {
    "name": "Kropa Waypoint",
    "chat": "[&BMwMAAA=]",
    "coord": [
      30312,
      102714
    ],
    "rect": [
      [
        29185,
        100890
      ],
      [
        33025,
        103450
      ]
    ]
  },
  "The Grove": {
    "name": "Upper Commons Waypoint",
    "chat": "[&BLoEAAA=]",
    "coord": [
      43162,
      37494
    ],
    "rect": [
      [
        42496,
        36480
      ],
      [
        43904,
        38528
      ]
    ]
  },
  "The Silverwastes": {
    "name": "Drydock Grotto Waypoint",
    "chat": "[&BLoHAAA=]",
    "coord": [
      38234,
      31108
    ],
    "rect": [
      [
        36608,
        30592
      ],
      [
        38656,
        32128
      ]
    ]
  },
  "The Wizard's Tower": {
    "name": "Tower Courtyard Waypoint",
    "chat": "[&BB8OAAA=]",
    "coord": [
      24103,
      22231
    ],
    "rect": [
      [
        23399,
        21882
      ],
      [
        24807,
        22650
      ]
    ]
  },
  "Thunderhead Peaks": {
    "name": "Moorage Waypoint",
    "chat": "[&BLoLAAA=]",
    "coord": [
      58150,
      36960
    ],
    "rect": [
      [
        55820,
        34936
      ],
      [
        59148,
        38648
      ]
    ]
  },
  "Timberline Falls": {
    "name": "Stromkarl Waypoint",
    "chat": "[&BEYEAAA=]",
    "coord": [
      52878,
      36203
    ],
    "rect": [
      [
        51712,
        34560
      ],
      [
        54016,
        37760
      ]
    ]
  },
  "Verdant Brink": {
    "name": "Pact Encampment Waypoint",
    "chat": "[&BAgIAAA=]",
    "coord": [
      35166,
      31785
    ],
    "rect": [
      [
        33408,
        30976
      ],
      [
        36608,
        32512
      ]
    ]
  },
  "Wayfarer Foothills": {
    "name": "Twinspur Haven Waypoint",
    "chat": "[&BH0BAAA=]",
    "coord": [
      55448,
      29751
    ],
    "rect": [
      [
        54528,
        27648
      ],
      [
        56320,
        32256
      ]
    ]
  }
};

export const REGION_MAPS: Record<string, string[]> = {
  "Ascalon": [
    "Black Citadel",
    "Blazeridge Steppes",
    "Diessa Plateau",
    "Fields of Ruin",
    "Fireheart Rise",
    "Grothmar Valley",
    "Iron Marches",
    "Plains of Ashford"
  ],
  "Cantha": [
    "Arborstone",
    "Dragon's End",
    "Gyala Delve",
    "Isle of Reflection",
    "Isle of Reflection",
    "Isle of Reflection",
    "Isle of Reflection",
    "Isle of Reflection",
    "New Kaineng City",
    "Seitung Province",
    "The Echovald Wilds"
  ],
  "Castora": [
    "Eternity's Garden",
    "Shipwreck Strand",
    "Starlit Weald"
  ],
  "Crystal Desert": [
    "Domain of Istan"
  ],
  "Heart of Maguuma": [
    "Auric Basin",
    "Bloodstone Fen",
    "Dragon's Stand",
    "Lost Precipice",
    "Lost Precipice",
    "Lost Precipice",
    "Lost Precipice",
    "Lost Precipice",
    "Tangled Depths",
    "Verdant Brink"
  ],
  "Horn of Maguuma": [
    "Amnytas",
    "Inner Nayos",
    "Skywatch Archipelago",
    "The Wizard's Tower"
  ],
  "Janthir": [
    "Bava Nisos",
    "Janthir Syntri",
    "Lowland Shore",
    "Mistburned Barrens"
  ],
  "Kryta": [
    "Bloodtide Coast",
    "Closing Ceremony",
    "Divinity's Reach",
    "Gendarran Fields",
    "Harathi Hinterlands",
    "Kessex Hills",
    "Lake Doric",
    "Lion's Arch",
    "Lion's Arch Aerodrome",
    "Queensdale",
    "Southsun Cove"
  ],
  "Maguuma Wastes": [
    "Dry Top",
    "The Silverwastes"
  ],
  "Ring of Fire": [
    "Draconis Mons",
    "Ember Bay"
  ],
  "Ruins of Orr": [
    "Cursed Shore",
    "Malchor's Leap",
    "Siren's Landing",
    "Straits of Devastation"
  ],
  "Shiverpeak Mountains": [
    "Bitterfrost Frontier",
    "Bjora Marches",
    "Dredgehaunt Cliffs",
    "Drizzlewood Coast",
    "Eye of the North",
    "Frostgorge Sound",
    "Hoelbrak",
    "Lornar's Pass",
    "Snowden Drifts",
    "Thunderhead Peaks",
    "Timberline Falls",
    "Wayfarer Foothills"
  ],
  "Steamspur Mountains": [
    "Labyrinthine Cliffs",
    "Mount Maelstrom",
    "Sparkfly Fen"
  ],
  "Tarnished Coast": [
    "Brisban Wildlands",
    "Caledon Forest",
    "Metrica Province",
    "Rata Sum",
    "The Grove"
  ]
};
