// AUTO-GENERATED by scripts/sync-map-waypoints.mjs — do not edit by hand.
// One representative waypoint per Tyria map (nearest the map centre) with its
// in-game chat code, plus a region -> map-names index. Source: GW2 API
// /v2/continents/1/floors/1 (chat_link is provided directly by the API).

export type MapWaypoint = { name: string; chat: string; coord: [number, number] };

export const MAP_WAYPOINTS: Record<string, MapWaypoint> = {
  "Amnytas": {
    "name": "Bastion of the Celestial Waypoint",
    "chat": "[&BAoOAAA=]",
    "coord": [
      24086,
      19984
    ]
  },
  "Arborstone": {
    "name": "Arborstone Waypoint",
    "chat": "[&BGMNAAA=]",
    "coord": [
      29845,
      101425
    ]
  },
  "Auric Basin": {
    "name": "Forgotten City Waypoint",
    "chat": "[&BMYHAAA=]",
    "coord": [
      34318,
      33966
    ]
  },
  "Bava Nisos": {
    "name": "Mantle's Arrival Waypoint",
    "chat": "[&BGEPAAA=]",
    "coord": [
      36051,
      11654
    ]
  },
  "Bitterfrost Frontier": {
    "name": "Sorrow's Eclipse Waypoint",
    "chat": "[&BH0JAAA=]",
    "coord": [
      54984,
      23970
    ]
  },
  "Bjora Marches": {
    "name": "Still Waters Speaking Waypoint",
    "chat": "[&BDkMAAA=]",
    "coord": [
      56616,
      17815
    ]
  },
  "Black Citadel": {
    "name": "Gladium Waypoint",
    "chat": "[&BKQDAAA=]",
    "coord": [
      57120,
      31106
    ]
  },
  "Blazeridge Steppes": {
    "name": "Refuge Sanctum Waypoint",
    "chat": "[&BAUCAAA=]",
    "coord": [
      62795,
      30752
    ]
  },
  "Bloodstone Fen": {
    "name": "Zealot's Overlook Waypoint",
    "chat": "[&BE4JAAA=]",
    "coord": [
      35482,
      30692
    ]
  },
  "Bloodtide Coast": {
    "name": "Firthside Vigil Waypoint",
    "chat": "[&BKoBAAA=]",
    "coord": [
      49401,
      34072
    ]
  },
  "Brisban Wildlands": {
    "name": "Brilitine Waypoint",
    "chat": "[&BGEAAAA=]",
    "coord": [
      40166,
      31857
    ]
  },
  "Caledon Forest": {
    "name": "Mabon Waypoint",
    "chat": "[&BDoBAAA=]",
    "coord": [
      42869,
      34533
    ]
  },
  "Closing Ceremony": {
    "name": "Crown Pavilion Waypoint",
    "chat": "[&BCwDAAA=]",
    "coord": [
      43628,
      27230
    ]
  },
  "Cursed Shore": {
    "name": "Meddler's Waypoint",
    "chat": "[&BB4DAAA=]",
    "coord": [
      43854,
      43752
    ]
  },
  "Diessa Plateau": {
    "name": "Blasted Moors Waypoint",
    "chat": "[&BNoAAAA=]",
    "coord": [
      57831,
      28790
    ]
  },
  "Divinity's Reach": {
    "name": "Palace Waypoint",
    "chat": "[&BCkDAAA=]",
    "coord": [
      44036,
      27193
    ]
  },
  "Domain of Istan": {
    "name": "Chalon Docks Waypoint",
    "chat": "[&BAkLAAA=]",
    "coord": [
      57793,
      61028
    ]
  },
  "Draconis Mons": {
    "name": "Ancient Hollow Waypoint",
    "chat": "[&BNUJAAA=]",
    "coord": [
      36589,
      41019
    ]
  },
  "Dragon's End": {
    "name": "Harvest Complex Waypoint",
    "chat": "[&BKAMAAA=]",
    "coord": [
      34181,
      103953
    ]
  },
  "Dragon's Stand": {
    "name": "Dragon's Domain Central Waypoint",
    "chat": "[&BJcIAAA=]",
    "coord": [
      35436,
      37715
    ]
  },
  "Dredgehaunt Cliffs": {
    "name": "Kenning Testing Ground Waypoint",
    "chat": "[&BF4CAAA=]",
    "coord": [
      53575,
      32721
    ]
  },
  "Drizzlewood Coast": {
    "name": "Forward Camp Waypoint",
    "chat": "[&BHIMAAA=]",
    "coord": [
      50444,
      19441
    ]
  },
  "Dry Top": {
    "name": "Restoration Refuge Waypoint",
    "chat": "[&BIgHAAA=]",
    "coord": [
      37731,
      32727
    ]
  },
  "Ember Bay": {
    "name": "Crumbling Trail Waypoint",
    "chat": "[&BGAJAAA=]",
    "coord": [
      39809,
      45115
    ]
  },
  "Eternity's Garden": {
    "name": "Sanctum Exterior Waypoint",
    "chat": "[&BPAPAAA=]",
    "coord": [
      4867,
      61003
    ]
  },
  "Eye of the North": {
    "name": "Eye of the North Waypoint",
    "chat": "[&BAkMAAA=]",
    "coord": [
      57865,
      21795
    ]
  },
  "Fields of Ruin": {
    "name": "Wreckage of Bloodgorge Watch Waypoint",
    "chat": "[&BE4BAAA=]",
    "coord": [
      63113,
      34430
    ]
  },
  "Fireheart Rise": {
    "name": "Keeper's Waypoint",
    "chat": "[&BCYCAAA=]",
    "coord": [
      58276,
      25871
    ]
  },
  "Frostgorge Sound": {
    "name": "Ridgerock Camp Waypoint",
    "chat": "[&BIMCAAA=]",
    "coord": [
      55253,
      26550
    ]
  },
  "Gendarran Fields": {
    "name": "Oogooth Waypoint",
    "chat": "[&BOIAAAA=]",
    "coord": [
      48089,
      29884
    ]
  },
  "Grothmar Valley": {
    "name": "Blood Keep Waypoint",
    "chat": "[&BBsMAAA=]",
    "coord": [
      60427,
      18848
    ]
  },
  "Gyala Delve": {
    "name": "Behemoth's Gap Waypoint",
    "chat": "[&BJINAAA=]",
    "coord": [
      37424,
      102153
    ]
  },
  "Harathi Hinterlands": {
    "name": "Recovery Camp Waypoint",
    "chat": "[&BKwAAAA=]",
    "coord": [
      47863,
      27455
    ]
  },
  "Hoelbrak": {
    "name": "Peeta's Waypoint",
    "chat": "[&BI8DAAA=]",
    "coord": [
      53314,
      30661
    ]
  },
  "Inner Nayos": {
    "name": "Forward Bivouac Waypoint",
    "chat": "[&BHYOAAA=]",
    "coord": [
      21734,
      22801
    ]
  },
  "Iron Marches": {
    "name": "Brandwatch Encampment Waypoint",
    "chat": "[&BOkBAAA=]",
    "coord": [
      61229,
      28081
    ]
  },
  "Isle of Reflection": {
    "name": "Reflection Docks Waypoint",
    "chat": "[&BPMMAAA=]",
    "coord": [
      21852,
      104468
    ]
  },
  "Janthir Syntri": {
    "name": "Sanguine Crater Waypoint",
    "chat": "[&BCwPAAA=]",
    "coord": [
      39237,
      15525
    ]
  },
  "Kessex Hills": {
    "name": "Viathan Waypoint",
    "chat": "[&BBAAAAA=]",
    "coord": [
      43834,
      31419
    ]
  },
  "Labyrinthine Cliffs": {
    "name": "Sky Docks Waypoint",
    "chat": "[&BB0HAAA=]",
    "coord": [
      55718,
      39278
    ]
  },
  "Lake Doric": {
    "name": "Doric's Landing Waypoint",
    "chat": "[&BK0JAAA=]",
    "coord": [
      45005,
      27002
    ]
  },
  "Lion's Arch": {
    "name": "Gate Hub Plaza Waypoint",
    "chat": "[&BBEEAAA=]",
    "coord": [
      49309,
      31223
    ]
  },
  "Lion's Arch Aerodrome": {
    "name": "Aerodrome Waypoint",
    "chat": "[&BCAJAAA=]",
    "coord": [
      49331,
      32137
    ]
  },
  "Lornar's Pass": {
    "name": "Afgar's Waypoint",
    "chat": "[&BFMGAAA=]",
    "coord": [
      51276,
      31884
    ]
  },
  "Lost Precipice": {
    "name": "Central Precipice Waypoint",
    "chat": "[&BMIIAAA=]",
    "coord": [
      34235,
      30348
    ]
  },
  "Lowland Shore": {
    "name": "Autumn's Vale Waypoint",
    "chat": "[&BC4PAAA=]",
    "coord": [
      41864,
      22648
    ]
  },
  "Malchor's Leap": {
    "name": "Blighted Arch Waypoint",
    "chat": "[&BK4CAAA=]",
    "coord": [
      45132,
      40523
    ]
  },
  "Metrica Province": {
    "name": "Rana Landing Complex Waypoint",
    "chat": "[&BEMAAAA=]",
    "coord": [
      40758,
      35413
    ]
  },
  "Mistburned Barrens": {
    "name": "Alliance Staging Ground",
    "chat": "[&BFAPAAA=]",
    "coord": [
      34312,
      11578
    ]
  },
  "Mount Maelstrom": {
    "name": "Oxbow Isle Waypoint",
    "chat": "[&BNECAAA=]",
    "coord": [
      52794,
      38992
    ]
  },
  "New Kaineng City": {
    "name": "Ministry Ward Waypoint",
    "chat": "[&BBkNAAA=]",
    "coord": [
      26674,
      99438
    ]
  },
  "Plains of Ashford": {
    "name": "Spirit Hunter Camp Waypoint",
    "chat": "[&BJkDAAA=]",
    "coord": [
      59896,
      30719
    ]
  },
  "Queensdale": {
    "name": "Scaver Waypoint",
    "chat": "[&BEUDAAA=]",
    "coord": [
      44145,
      29194
    ]
  },
  "Rata Sum": {
    "name": "Auxiliary Waypoint",
    "chat": "[&BLkEAAA=]",
    "coord": [
      38746,
      37236
    ]
  },
  "Seitung Province": {
    "name": "Daigo Ward Waypoint",
    "chat": "[&BGUNAAA=]",
    "coord": [
      23191,
      101452
    ]
  },
  "Shipwreck Strand": {
    "name": "Hullgarden Pier Waypoint",
    "chat": "[&BMwPAAA=]",
    "coord": [
      11661,
      59029
    ]
  },
  "Siren's Landing": {
    "name": "Camp Reclamation Waypoint",
    "chat": "[&BO8JAAA=]",
    "coord": [
      49393,
      42605
    ]
  },
  "Skywatch Archipelago": {
    "name": "Kestrel's Vow Waypoint",
    "chat": "[&BD8OAAA=]",
    "coord": [
      25402,
      23928
    ]
  },
  "Snowden Drifts": {
    "name": "Torstvedt Homestead Waypoint",
    "chat": "[&BLsAAAA=]",
    "coord": [
      52847,
      28439
    ]
  },
  "Southsun Cove": {
    "name": "Camp Karka Waypoint",
    "chat": "[&BNcGAAA=]",
    "coord": [
      45606,
      36767
    ]
  },
  "Sparkfly Fen": {
    "name": "Toade's Head Waypoint",
    "chat": "[&BMsBAAA=]",
    "coord": [
      49398,
      37058
    ]
  },
  "Starlit Weald": {
    "name": "Priory Expedition Waypoint",
    "chat": "[&BJ4PAAA=]",
    "coord": [
      7618,
      58836
    ]
  },
  "Straits of Devastation": {
    "name": "Vesper Bell Waypoint",
    "chat": "[&BPICAAA=]",
    "coord": [
      49073,
      40069
    ]
  },
  "Tangled Depths": {
    "name": "Ogre Camp Waypoint",
    "chat": "[&BMwHAAA=]",
    "coord": [
      36674,
      35238
    ]
  },
  "The Echovald Wilds": {
    "name": "Kropa Waypoint",
    "chat": "[&BMwMAAA=]",
    "coord": [
      30312,
      102714
    ]
  },
  "The Grove": {
    "name": "Upper Commons Waypoint",
    "chat": "[&BLoEAAA=]",
    "coord": [
      43162,
      37494
    ]
  },
  "The Silverwastes": {
    "name": "Drydock Grotto Waypoint",
    "chat": "[&BLoHAAA=]",
    "coord": [
      38234,
      31108
    ]
  },
  "The Wizard's Tower": {
    "name": "Tower Courtyard Waypoint",
    "chat": "[&BB8OAAA=]",
    "coord": [
      24103,
      22231
    ]
  },
  "Thunderhead Peaks": {
    "name": "Moorage Waypoint",
    "chat": "[&BLoLAAA=]",
    "coord": [
      58150,
      36960
    ]
  },
  "Timberline Falls": {
    "name": "Stromkarl Waypoint",
    "chat": "[&BEYEAAA=]",
    "coord": [
      52878,
      36203
    ]
  },
  "Verdant Brink": {
    "name": "Pact Encampment Waypoint",
    "chat": "[&BAgIAAA=]",
    "coord": [
      35166,
      31785
    ]
  },
  "Wayfarer Foothills": {
    "name": "Twinspur Haven Waypoint",
    "chat": "[&BH0BAAA=]",
    "coord": [
      55448,
      29751
    ]
  }
};

export const REGION_MAPS: Record<string, string[]> = {
  "Ascalon": [
    "Black Citadel",
    "Blazeridge Steppes",
    "Diessa Plateau",
    "Fields of Ruin",
    "Fireheart Rise",
    "Grothmar Valley",
    "Iron Marches",
    "Plains of Ashford"
  ],
  "Cantha": [
    "Arborstone",
    "Dragon's End",
    "Gyala Delve",
    "Isle of Reflection",
    "Isle of Reflection",
    "Isle of Reflection",
    "Isle of Reflection",
    "Isle of Reflection",
    "New Kaineng City",
    "Seitung Province",
    "The Echovald Wilds"
  ],
  "Castora": [
    "Eternity's Garden",
    "Shipwreck Strand",
    "Starlit Weald"
  ],
  "Crystal Desert": [
    "Domain of Istan"
  ],
  "Heart of Maguuma": [
    "Auric Basin",
    "Bloodstone Fen",
    "Dragon's Stand",
    "Lost Precipice",
    "Lost Precipice",
    "Lost Precipice",
    "Lost Precipice",
    "Lost Precipice",
    "Tangled Depths",
    "Verdant Brink"
  ],
  "Horn of Maguuma": [
    "Amnytas",
    "Inner Nayos",
    "Skywatch Archipelago",
    "The Wizard's Tower"
  ],
  "Janthir": [
    "Bava Nisos",
    "Janthir Syntri",
    "Lowland Shore",
    "Mistburned Barrens"
  ],
  "Kryta": [
    "Bloodtide Coast",
    "Closing Ceremony",
    "Divinity's Reach",
    "Gendarran Fields",
    "Harathi Hinterlands",
    "Kessex Hills",
    "Lake Doric",
    "Lion's Arch",
    "Lion's Arch Aerodrome",
    "Queensdale",
    "Southsun Cove"
  ],
  "Maguuma Wastes": [
    "Dry Top",
    "The Silverwastes"
  ],
  "Ring of Fire": [
    "Draconis Mons",
    "Ember Bay"
  ],
  "Ruins of Orr": [
    "Cursed Shore",
    "Malchor's Leap",
    "Siren's Landing",
    "Straits of Devastation"
  ],
  "Shiverpeak Mountains": [
    "Bitterfrost Frontier",
    "Bjora Marches",
    "Dredgehaunt Cliffs",
    "Drizzlewood Coast",
    "Eye of the North",
    "Frostgorge Sound",
    "Hoelbrak",
    "Lornar's Pass",
    "Snowden Drifts",
    "Thunderhead Peaks",
    "Timberline Falls",
    "Wayfarer Foothills"
  ],
  "Steamspur Mountains": [
    "Labyrinthine Cliffs",
    "Mount Maelstrom",
    "Sparkfly Fen"
  ],
  "Tarnished Coast": [
    "Brisban Wildlands",
    "Caledon Forest",
    "Metrica Province",
    "Rata Sum",
    "The Grove"
  ]
};
